### ISSUE TITLE
Function Suggestion: Load function to load text

### ISSUE THREAD

**Issue by yohan-choi-dev** [Reza-Rajabi/nOTeTOn#4]
Hello, I found out that even though we save write something, but there is no way to load stored. I suggest adding a load function, then this would be more wonderful!

**Comment by Reza-Rajabi** [comment]
Hi.
Yes, that would be great if we can write on/load from a file.

**Comment by Reza-Rajabi** [comment]
Resolved with [this PR](https://github.com/Reza-Rajabi/nOTeTOn/pull/5)
